apiVersion: v1
kind: Service
metadata:
  name: kubernetes-lite-deploy
spec:
  selector:
    app: kubernetes-lite-deploy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
